os: linux
language: cpp

dist: bionic

compiler:
    - gcc
    - clang

branches:
    only: 
    - /.*/

install:
    # Install CMake 3.17
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
    - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-Linux-x86_64.tar.gz
    - tar -xvf cmake-3.17.2-Linux-x86_64.tar.gz > /dev/null
    - mv cmake-3.17.2-Linux-x86_64 cmake-install
    - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
    - cd ${TRAVIS_BUILD_DIR}

script:
    - mkdir build && cd build
    - ${DEPS_DIR}/cmake-install/bin/cmake ..
    - ${DEPS_DIR}/cmake-install/bin/cmake --build  .
    - fetchContent_example
