os: linux
language: cpp

dist: bionic

compiler:
    - gcc
    - clang

branches:
    only: 
    - /.*/

before_script:
    - ./install_cmake.sh
script:
    - mkdir build && cd build
    - /usr/local/bin/cmake ..
    - /usr/local/bin/cmake --build  .
    - fetchContent_example
